# Generated by Django 4.2.6 on 2023-12-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='hour',
            new_name='hours',
        ),
    ]
