# Generated by Django 4.2.6 on 2023-12-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('module', '0002_rename_hour_module_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='page.page'),
        ),
    ]
