# Generated by Django 4.2.6 on 2023-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('module', '0003_module_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignments',
            field=models.ManyToManyField(to='assignment.assignment'),
        ),
    ]
