# Generated by Django 4.2.6 on 2023-12-29 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0004_module_assignments'),
        ('question', '0001_initial'),
        ('classroom', '0004_course_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(null=True, to='module.module'),
        ),
        migrations.AlterField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(null=True, to='question.question'),
        ),
    ]
