# Generated by Django 4.2.6 on 2023-12-29 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('module', '0004_module_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0005_alter_course_enrolled_alter_course_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='module.module'),
        ),
        migrations.AlterField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(to='question.question'),
        ),
    ]
